# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20161010_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('answerid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
    ]
