# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20161010_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lastquestionansweredid', models.CharField(max_length=100)),
                ('timeanswered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='questiontext',
            field=models.CharField(max_length=100),
        ),
    ]
