# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20161010_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='lastquestionansweredid',
            new_name='currentquestion',
        ),
        migrations.RenameField(
            model_name='ranking',
            old_name='timeanswered',
            new_name='timestarted',
        ),
    ]
