# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20161012_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hint1',
            field=models.CharField(default='No Hints', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='imagelink',
            field=models.CharField(default='No Image', max_length=300),
        ),
    ]
